// Broad print-mode and RTL smoke test for the public content-box families.
#import "../lib.typ": *
#import "../src/blocks.typ": banner, answer, frac
#set page(width: 18cm, height: auto, margin: 0.8cm)
#set text(lang: "ar", dir: rtl, font: "DejaVu Sans", size: 9pt)
#set par(leading: 0.48em)
#show: faboxyst.with(theme: "print")

#grid(columns: (1fr, 1fr), column-gutter: 0.35cm, row-gutter: 0.35cm,
  numbered-header-box(title: [عنوان مرقّم], number: 12, direction: rtl)[محتوى RTL في نمط الطباعة.],
  garnet-box(direction: rtl)[لافتة مطبوعة.],
  postit(title: [ملاحظة], direction: rtl)[ورقة لاصقة مطبوعة.],
  postit-butterfly(title: [ملاحظة أخرى], direction: rtl)[ورقة ذات جناح مطبوعة.],
  sketch-box(fill: rgb("#F3C832"), stroke-colour: red)[رسم يدوي.],
  fabox(title: [مربع معياري], colour: blue, shadow: "large")[مربع معياري.],
  fabox(title: [تحذير], border: "caution", halo: (0.12, yellow), gradient-to: red, watermark: [!] )[ملء مخصص يصبح أحادي اللون.],
  fabox-sign[تنبيه],
  fabox-note[ملاحظة مطبوعة.],
  def-card([التعريف], [بطاقة تعريف RTL.]),
  banner([إجابة مهمة], icon: [❕], direction: rtl),
  answer([١٢], [الإجابة المطبوعة.]),
  frac(3, 4),
  sticky[ملاحظة لاصقة.],
  iconbox(title: [مفهوم], banner: true, direction: rtl)[بطاقة مفهوم.],
  calloutbox(title: [تنبيه], direction: rtl)[فقاعة شرح.],
  circuitbox(title: [دائرة], direction: rtl)[لوحة دائرة.],
  keybox(direction: rtl)[إطار مفتاحي.],
  lacebox(title: [زخرفة], direction: rtl)[إطار زخرفي.],
  ringbox(direction: rtl)[دفتر بحلقات.],
  stackbox(title: [طبقات], direction: rtl)[بطاقة ذات طبقات.],
  stubbox(stub: [12], direction: rtl)[تذكرة مطبوعة.],
  tapebox(title: [شريط], direction: rtl)[ورقة مع شريط.],
  ribbonbox(title: [شارة], direction: rtl)[شريط مطبوع.],
  boardbox(title: [لوح], direction: rtl)[محتوى على اللوح.],
  chalkbox[سطح طباشيري.],
  markerbox[سطح أقلام.],
  coilbox(title: [دفتر], direction: rtl)[دفتر حلزوني.],
  notebook-box-clean[صفحة نظيفة مطبوعة.],
  flagbox(title: [عنوان], direction: rtl)[شريط عنوان.],
  notebook-box(title: [دفتر])[صفحة دفتر.],
  filebox(direction: rtl)[ملف أوراق.],
  screwbox(direction: rtl)[لوحة بمسامير.],
  numbox(title-colour: black, direction: rtl)[تمرين مرقّم.],
  plannerbox(title: [مخطط], number: [٣], direction: rtl)[مخطط أسبوعي.],
  punchbox(title: [ثقوب], number: [٤], direction: rtl)[صفحة مثقوبة.],
  crestbox(title: [شعار], direction: rtl)[لوحة شعار.],
  swooshbox(title: [بطاقة مائلة], direction: rtl)[بطاقة مائلة.],
  helixbox(title: [حلزون], direction: rtl)[بنية لولبية.],
  sashbox(direction: rtl)[شريط مائل.],
  plankbox(title: [لوح خشبي], direction: rtl)[لوح مطبوع.],
  tornpage(title: [ورقة ممزقة], direction: rtl)[ورقة مطبوعة.],
  gelbox[زر مطبوع],
  ogeebox(badge: 7)[إطار مقوّس.],
  frisebox(fill: red, line: blue, text-fill: white)[شريط مطبوع.],
  khatambox(title: [خاتم], badge: [٧], direction: rtl)[إطار مزخرف.],
  zellijbox(title: [زليج], direction: rtl)[إطار هندسي.],
  fleuronbox(title: [زخرفة], direction: rtl)[إطار زخرفي.],
  rosettebox(title: [وردة], direction: rtl)[إطار وردي.],
  speech-bubble(direction: rtl)[فقاعة مطبوعة.],
  leconbox(num: 2)[درس مطبوع.],
  pinbox[السنة الأولى][المعلومات الإضافية],
  brushbox[شريط الفرشاة.],
  matierebox(subject: [مادة], year: [2026], body: [بطاقة مادة.]),
  torn-note(width: 7)[ملاحظة ممزقة.],
  ruled-sheet(width: 7)[ورقة مسطرة.],
  stamp-card(width: 7)[بطاقة طابع.],
  grid-note(width: 7)[ملاحظة مربعات.],
  index-card(width: 7, heading: [فهرس])[بطاقة فهرسة.],
  deckle-tag(width: 7)[بطاقة ممزقة الحواف.],
  notepad(width: 7)[مفكرة مطبوعة.],
  lesson-card(width: 7, title: [درس])[بطاقة درس.],
  post-it(title: [لاصقة])[ورقة لاصقة قديمة.],
  ticket(stub: [١٢])[تذكرة مطبوعة.],
  sloppy-box(fill: red)[إطار عفوي مطبوع.],
  spread-box(title: [كتاب مفتوح], colour: blue, fill: red, gradient-to: yellow)[صفحتان مطبوعتان.],
  folder(title: [ملف])[محتوى الملف.],
  terminal(title: [طرفية])[ls -la],
  neon[لوحة نيون مطبوعة.],
  polaroid(caption: [صورة])[صورة مطبوعة.],
  vintagebox[لوحة عتيقة مطبوعة.],
  ornatebox(title: [مؤطّر])[إطار مزخرف مطبوع.],
  volutebox[إطار حلزوني مطبوع.],
  parchemin(title: [رسالة])[رسالة مطبوعة.],
  insetbox[صندوق داخلي مطبوع.],
)
