#import "../lib.typ": *
#set page(width: 20cm, height: auto, margin: 1cm)
#show: faboxyst.with(theme: themes.notebook)
#let L = [Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh.]
#let AR = [نص عربي تجريبي لاختبار اتجاه الكتابة من اليمين إلى اليسار.]
#let S3 = ((title: [Analysis], body: L, icon: [★]), (title: [Plan], body: L, icon: [✦]), (title: [Build], body: L, icon: [●]))
#let A3 = ((title: [التحليل], body: AR, icon: [★]), (title: [التخطيط], body: AR, icon: [✦]), (title: [البناء], body: AR, icon: [●]))
#puzzle-tab-cards(steps: S3)
#v(3mm)
#puzzle-tab-cards(steps: A3)
#v(3mm)
#folded-tab-cards(steps: S3)
#v(3mm)
#folded-tab-cards(steps: A3)
#v(3mm)
#half-disc-tab-cards(steps: S3)
#v(3mm)
#half-disc-tab-cards(steps: A3)
#v(3mm)
#u-backed-cards(steps: S3)
#v(3mm)
#u-backed-cards(steps: A3)
#v(3mm)
#circle-head-outline-cards(steps: S3)
#v(3mm)
#circle-head-outline-cards(steps: A3)
#v(3mm)
#dashed-pill-cards(steps: S3)
#v(3mm)
#dashed-pill-cards(steps: A3)
#v(3mm)
#skewed-badge-cards(steps: S3)
#v(3mm)
#skewed-badge-cards(steps: A3)
#v(3mm)
#badge-timeline-cards(steps: S3)
#v(3mm)
#badge-timeline-cards(steps: A3)
#v(3mm)

