#import "../lib.typ": *
#set page(width: 20cm, height: auto, margin: 1cm)
#show: faboxyst.with(theme: themes.notebook)
#let L = [Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh.]
#let AR = [نص عربي تجريبي لاختبار اتجاه الكتابة من اليمين إلى اليسار.]
#let S3 = ((title: [Analysis], body: L, icon: [★]), (title: [Plan], body: L, icon: [✦]), (title: [Build], body: L, icon: [●]))
#let A3 = ((title: [التحليل], body: AR, icon: [★]), (title: [التخطيط], body: AR, icon: [✦]), (title: [البناء], body: AR, icon: [●]))
#ring-linked-boxes(steps: S3)
#v(3mm)
#ring-linked-boxes(steps: A3)
#v(3mm)
#wire-linked-pills(steps: S3)
#v(3mm)
#wire-linked-pills(steps: A3)
#v(3mm)
#brush-stroke-rows(steps: S3)
#v(3mm)
#brush-stroke-rows(steps: A3)
#v(3mm)
#twisted-ribbon-rows(steps: S3)
#v(3mm)
#twisted-ribbon-rows(steps: A3)
#v(3mm)
#bubble-tail-boxes(steps: S3)
#v(3mm)
#bubble-tail-boxes(steps: A3)
#v(3mm)
#striped-poster-cards(steps: S3)
#v(3mm)
#striped-poster-cards(steps: A3)
#v(3mm)
#pencil-frame-flow([#text(18pt, weight: "bold")[PROJECT]], steps: ([Plan], [Do], [Check], [Act]), width: 9cm)
#v(3mm)
#index-notebook(title: [PLAN], steps: S3)
#v(3mm)
#index-notebook(title: [الخطة], steps: A3)
#v(3mm)
#film-strip(frames: ([One], [Two], [Three], [Four]))
#v(3mm)
#chevron-slideshow-frame([Slide], width: 12cm)

